### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by Rutul27** [jclarke0000/MMM-MyCommute#17]
I cloned and configured the module correctly, there're two problems:
1. 'this api project is not authorized to use this api'
2. it just keeps loading

my project is using directional api instead of maps javascript api (I checked this on the cloud platform).

Any help/suggestion is appreciated.

**Comment by cayers71** [comment]
Just solved this issue myself.  Make sure that the 'Directions' API is enabled for your key...once I enabled it, the module worked correctly.
