### ISSUE TITLE
Is there a way to change the refresh rate in config?

### ISSUE THREAD

**Issue by pyrosmiley** [jclarke0000/MMM-MyCommute#4]
Even without it running 24h, I've hit the rate limit for the maps API a few times already, but I'd like to not have to to change it every time there's an update. 

If not, no big deal! Still really appreciate the work on this.

**Comment by jclarke0000** [comment]
I'll add a config for this.  Meanwhile if you want to change this yourself in the interim, you can modify the file `MMM-MyCommute.js` on line 128:

`POLL_FREQUENCY : 10 * 60 * 1000, //poll every 10 minutes`

This expects a value in milliseconds.  To change this to every 15 minutes, for example, you can set this to `15 * 60 * 1000` or simply `900000`.

**Comment by jclarke0000** [comment]
I added a config option named `pollFrequency` where you can set this to whatever you want.

**Comment by pyrosmiley** [comment]
perfect!! Thank you so much -- I had edited the value in the main script after some poking around, but I'm trying to build this as a gift for a non-tech-savvy relative, so the fewer potential breakpoints it has, the better.
